config/routes.rb
Rails.application.routes.draw do
  resources :paths

  root 'pages#home'

  get 'pages/about'

end

app/models/path.rb
class Path < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/paths_controller.rb
class PathsController < ApplicationController
  before_action :set_path, only: [:show, :edit, :update, :destroy]

  # GET /paths
  # GET /paths.json
  def index
    @paths = Path.all
  end

  # GET /paths/1
  # GET /paths/1.json
  def show
  end

  # GET /paths/new
  def new
    @path = Path.new
  end

  # GET /paths/1/edit
  def edit
  end

  # POST /paths
  # POST /paths.json
  def create
    @path = Path.new(path_params)

    respond_to do |format|
      if @path.save
        format.html { redirect_to @path, notice: 'Path was successfully created.' }
        format.json { render :show, status: :created, location: @path }
      else
        format.html { render :new }
        format.json { render json: @path.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paths/1
  # PATCH/PUT /paths/1.json
  def update
    respond_to do |format|
      if @path.update(path_params)
        format.html { redirect_to @path, notice: 'Path was successfully updated.' }
        format.json { render :show, status: :ok, location: @path }
      else
        format.html { render :edit }
        format.json { render json: @path.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paths/1
  # DELETE /paths/1.json
  def destroy
    @path.destroy
    respond_to do |format|
      format.html { redirect_to paths_url, notice: 'Path was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_path
      @path = Path.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def path_params
      params.require(:path).permit(:title, :descrition)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/paths_helper.rb
module PathsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ratatooy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_url %>">ratatooy</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     
     
      <ul class="nav navbar-nav navbar-right">
        
        <li><%= link_to 'Accueil' , root_path %></li>
        <li><%= link_to 'A propos' , pages_about_path %></li>
        <li><a href="#">Inscription</a></li>
        <li><a href="#">Connexion</a></li>
        <li><%= link_to 'Proposer votre jardin' , paths_path, class: "btn btn-success btn-xs" %></li>
        

      
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About ratatooy</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1>Bienvenue sur ratatooy</h1>
<p class= "description">Trouvez un potager près de chez vous et cultivez vos propres légumes</p>
  <p>
  	<%= link_to 'A propos' , pages_about_path, class: "btn btn-primary" %>
  	<%= link_to 'Proposer votre jardin' , paths_path, class: "btn btn-success" %>
  </p>
</div>

app/views/paths/_form.html.erb
<%= form_for(@path) do |f| %>
  <% if @path.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@path.errors.count, "error") %> prohibited this path from being saved:</h2>

      <ul>
      <% @path.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :descrition %><br>
    <%= f.text_area :descrition %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paths/edit.html.erb
<h1>Editing Path</h1>

<%= render 'form' %>

<%= link_to 'Show', @path %> |
<%= link_to 'Back', paths_path %>

app/views/paths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proposer votre jardin</h1>

<br>

<%= link_to 'New Path', new_path_path, class: "btn btn-primary pull-right" %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Descrition</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paths.each do |path| %>
      <tr>
        <td><%= path.title %></td>
        <td><%= path.descrition %></td>
        <td><%= link_to 'Show', path %></td>
        <td><%= link_to 'Edit', edit_path_path(path) %></td>
        <td><%= link_to 'Destroy', path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/paths/new.html.erb
<h1>New Path</h1>

<%= render 'form' %>

<%= link_to 'Back', paths_path %>

app/views/paths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @path.title %>
</p>

<p>
  <strong>Descrition:</strong>
  <%= @path.descrition %>
</p>

<%= link_to 'Edit', edit_path_path(@path) %> |
<%= link_to 'Back', paths_path %>